### ISSUE TITLE
Subscribe to a zipped model broken ?

### ISSUE THREAD

**Issue by mmcoulombe** [suzaku-io/diode#58]
Hi guys, 

I was wondering if it's an issue or a desired behavior. I'm trying to subscribe to a zipped model but the update is never trigger. I've also try to override the implicits FastEq but nothing can do.

Here is what I've done to create this issue:
```scala
 // model
case class Model(name: String, desc: String)
// action
case class ChangeName(name: String) extends Action
case class ChangeDesc(desc: String) extends Action
// circuit
object AppCircuit extends Circuit[Model] {
  def initialModel = Model("", "")

  def actionHandler: AppCircuit.HandlerFunction =
    (model, action) => action match {
      case ChangeName(a) => Some(ModelUpdate(model.copy( name = a )))
      case ChangeDesc(a) => Some(ModelUpdate(model.copy( desc = a )))
      case ChangeBoth(a, b) => Some(ModelUpdate(model.copy(name = a, desc = b)))
    }
}
// test
val nameReader = AppCircuit.zoom(_.name)
val descReader = AppCircuit.zoom(_.desc)
val zipped = nameReader.zip(descReader)

AppCircuit.subscribe(zipped)(a => {
  println(s"Someting has change: ${a.value}") // never called
})
AppCircuit.dispatch(ChangeName("a name"))
AppCircuit.dispatch(ChangeBoth("a name", "a description"))
```

**Comment by ochrons** [comment]
This is kind of expected behavior because your zipper is not part of the model and is not automatically updated when the model changes. The zipper is not re-evaluated as part of the listener update check and therefore it will remain equal to the previous value, even though it would actually change if it were evaluated. The subscription mechanism was designed to work with readers that point to actual model values only, so this case is currently not supported.

I suppose it would make sense to be able to subscribe to changes using derivative readers too, which would require changing `ZipModelR` `===` method to something like

```scala
override def ===(that: (S, SS)) = 
  feqS.neqv(get1(root.value), that._1) && feqSS.neqv(get2(root.value), that._2)
```
If you don't mind testing if that would fix the issue, I'm more than happy to receive a small PR 😄

**Comment by mmcoulombe** [comment]
Thanks for the clarification!

I'll test your solution and gladly provide a PR. :smiley:
