### ISSUE TITLE
RefTo yields property of null error

### ISSUE THREAD

**Issue by Taig** [suzaku-io/diode#74]
I'm not entirely confident that my usage of `RefTo` is correct here, but what I saw from the documentation I assume it might be a good fit for my use case. I added a simplified example that [demonstrates the error on ScalaFiddle](https://scalafiddle.io/sf/RO0b4of/1).

**Comment by ochrons** [comment]
This is probably an initialization order problem, where your code tries to read the Circuit model before it has finished initializing. You cannot call any of the `zoom` functions within the `initialModel` method because `initialModel` is used to initialize the model :)

To work around this, you need to initialize the ref later, for example by making it a function [like this](https://scalafiddle.io/sf/RO0b4of/2)

**Comment by Taig** [comment]
Thank you, I somehow expected that `RefTo` had some kind of lazy evaluation baked in already. But your solution works for me 👍
